### ISSUE TITLE
Garantie d'unicité ? 

### ISSUE THREAD

**Issue by joelgombin** [geoffreyaldebert/heidi#3]
Bonjour,

le générateur garantit-il que chacun des identifiants générés, tout au long de sa vie, est unique, ou bien cette garantie n'existe-t-elle qu'au moment de sa génération ? (je ne sais pas si ma question est claire)
par ailleurs est-il possible de l'interroger par API ?

**Comment by geoffreyaldebert** [comment]
Bonjour Joel,

L'identifiant généré par cet applicatif est un identifiant `uuid` basé sur [ces spécifications](https://fr.wikipedia.org/wiki/Universally_unique_identifier#:~:text=Universally%20unique%20identifier%20(UUID)%2C,information%20sans%20coordination%20centrale%20importante.). C'est un standard très couramment utilisé pour la gestion d'identifiant unique en informatique.

Il existe 10^38 possibilités d'identifiants, donc il est considéré comme unique, même si en réalité il est *très probablement unique*.

Par contre, si ta question porte sur la réutilisation de cet identifiant pour identifier deux données différentes, là oui nous ne pouvons pas le garantir. Cela dépend de l'usage fait par le réutilisateur de cet identifiant.

Bien à toi, n'hésite pas si tu souhaites un complément,
Geoffrey

**Comment by joelgombin** [comment]
Merci pour les précisions ! c'est très clair. peut-être mériteraient-elles d'être dans le README de ce repo et/ou sur le site ?
